#!/usr/bin/env node
// Precondition helper for walk.js (docs/issues/U19-A4-oai-last-part-offers-resume.md):
// the report's precondition is `oai_max_records = 1` under `[oai]` in the
// install's config.inc.php, because the default dataset's lists are shorter
// than one answer (100). The dataset fleet's own config is generated inside
// the app checkout and regenerated by every reset, so this helper leaves it
// alone: it restarts the fleet's server on the same port with a copy of that
// config, the one key changed, kept under .reports/.
//
//   PKP_E2E_DATASET=1 node shared/playwright/checks/issues/oai-last-part-offers-resume/serve.js on  [ojs omp ops]
//   PKP_E2E_DATASET=1 node shared/playwright/checks/issues/oai-last-part-offers-resume/serve.js off [ojs omp ops]
//
// `off` puts the fleet's own server back (probe-servers --stop, --start).
// PKP_E2E_LINE=<line> in front works on a stable line's fleet.
const fs = require('fs');
const path = require('path');
const {spawn, execFileSync} = require('child_process');
const REPO_ROOT = path.resolve(__dirname, '../../../../..');
const {resolveLine} = require(path.join(REPO_ROOT, 'bin/apps.js'));
const {datasetFleet} = require(path.join(REPO_ROOT, 'shared/playwright/dataset.js'));
const {phpServerCommand, phpServerEnv, phpServerStatus} = require(path.join(REPO_ROOT, 'shared/playwright/php-server.js'));

const [mode, ...names] = process.argv.slice(2);
const apps = names.length ? names : ['ojs', 'omp', 'ops'];
const n = Number(process.env.PKP_E2E_DATASET || 1);
const line = resolveLine();
const pidDir = path.join(REPO_ROOT, '.reports', line ? `servers-${line.name}` : 'servers');
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

function probeServers(action, app) {
    execFileSync('node', ['bin/probe-servers.js', `--${action}`, '--app', app, '--dataset', String(n)], {
        cwd: REPO_ROOT,
        stdio: 'inherit',
    });
}

async function on(name) {
    const fleet = datasetFleet(name, n);
    const text = fs.readFileSync(fleet.configFile, 'utf8');
    if (!/^oai_max_records\s*=.*$/m.test(text)) throw new Error(`${name}: no oai_max_records in ${fleet.configFile}`);
    const outDir = path.join(REPO_ROOT, '.reports', 'issues-u19-a4');
    fs.mkdirSync(outDir, {recursive: true});
    const configFile = path.join(outDir, `config-${line ? line.name : 'main'}-${name}-ds${n}.inc.php`);
    fs.writeFileSync(configFile, text.replace(/^oai_max_records\s*=.*$/m, 'oai_max_records = 1'));
    probeServers('stop', name);
    const root = path.resolve(REPO_ROOT, fleet.root || path.dirname(fleet.configFile));
    const logFile = path.join(REPO_ROOT, 'apps', name, 'playwright', '.server-logs', `server-${fleet.port}-ds${n}.log`);
    const child = spawn('sh', ['-c', phpServerCommand({appRoot: root, port: fleet.port, logFile})], {
        cwd: REPO_ROOT,
        detached: true,
        stdio: 'ignore',
        env: {...process.env, ...phpServerEnv({configFile, testApiKey: fleet.testApiKey})},
    });
    child.unref();
    // The fleet's own pid file, so `probe-servers --stop --dataset n` stops this one too.
    fs.writeFileSync(path.join(pidDir, `probe-${name}-ds${n}.pid`), `${child.pid}\n`);
    for (let i = 0; i < 60 && (await phpServerStatus(fleet.port)) === null; i++) await sleep(500);
    console.log(`serve: ${name} ds${n} on ${fleet.port} with oai_max_records = 1 (${path.relative(REPO_ROOT, configFile)})`);
}

(async () => {
    for (const name of apps) {
        if (mode === 'on') await on(name);
        else if (mode === 'off') {
            probeServers('stop', name);
            probeServers('start', name);
        } else throw new Error('usage: serve.js on|off [ojs omp ops]');
    }
})().catch((e) => {
    console.error(e.message);
    process.exit(1);
});
