// Prints a short cross-app digest of .reports/U62/ccK1/k1-facts-<app>.json (run after k1.js).
const fs = require('fs');
const path = require('path');
const dir = path.resolve(__dirname, '../../../../../.reports/U62', process.env.PROBE_AGENT || 'ccK1');
const b = (r) => (r ? `${r.checked ? 'x' : '-'}${r.disabled ? 'L' : ''}${r.arrow ? '>' : ''}` : 'absent');
const t = (a) => (a || []).map((x) => (x.text || '').replace(/ × Close/, '')).filter(Boolean)[0] || 'none';
for (const app of ['ojs', 'omp', 'ops']) {
    const p = path.join(dir, `k1-facts-${app}.json`);
    if (!fs.existsSync(p)) continue;
    const f = JSON.parse(fs.readFileSync(p, 'utf8'));
    console.log(`\n===== ${app}: phases ${Object.keys(f).join(',')}`);
    if (f.roles) for (const [k, r] of Object.entries(f.roles)) console.log(`roles ${k}: ${r.denied ? 'DENIED ' + r.url : `tab=${r.pluginsTab} inner=${(r.innerTabs || []).join('/')} hdr=${(r.headerLinks || []).join('/')} rows=${r.rows} arrows=${r.withArrow} usage=${b(r.usageEvent)} wf=${JSON.stringify(r.links && r.links.webfeedplugin && r.links.webfeedplugin.links)} gs=${JSON.stringify(r.links && r.links.googlescholarplugin)} lockedUnticked=${JSON.stringify(r.lockedUnticked)} gallery=${r.gallery}`}`);
    if (f.roles && f.roles.mgr) console.log('mgr grid:\n  ' + (f.roles.mgr.grid || []).join('\n  '));
    if (f.search) { const s = f.search; console.log(`search: formAtLanding=${s.formVisibleAtLanding} afterLink=${s.formVisibleAfterLink}`); for (const k of ['feed', 'FEED', 'none', 'enter', 'block', 'blockFeed', 'all']) if (s[k]) console.log(`  ${k}: fv=${s[k].filterVisible} ${JSON.stringify(s[k].grid).slice(0, 400)}`); console.log('  leave', JSON.stringify(s.leave), JSON.stringify(s.afterReturn)); }
    if (f.switch) { const s = f.switch; console.log(`switch: tickGA window=${JSON.stringify(s.tickGA.window)} toast=${t(s.tickGA.toast)} @${s.tickGA.toast[0] && s.tickGA.toast[0].x},${s.tickGA.toast[0] && s.tickGA.toast[0].y} after=${s.tickGA.after} reload=${b(s.gaAfterReload)}`); console.log(`  cancel: window=${JSON.stringify(s.cancelWF.window)} toast=${t(s.cancelWF.toast)} after=${s.cancelWF.after} reload=${b(s.wfAfterCancelReload)} traffic=${s.cancelWF.traffic}`); console.log(`  ok: toast=${t(s.okWF.toast)} after=${s.okWF.after} reload=${b(s.wfAfterOkReload)}; retick ${s.retickWF.after}; locked=${String(s.lockedClick).slice(0, 60)} ${s.lockedAfter}; ed ${s.edTick && t(s.edTick.toast)} / ${s.edUntick && t(s.edUntick.toast)}`); }
    if (f.separate) { const s = f.separate; console.log(`separate: Y ga=${b(s.Y && s.Y.ga)} siteTab=${s.sitePluginsTab} site ga=${b(s.site && s.site.ga)} usage=${b(s.site && s.site.usage)} cbm=${b(s.site && s.site.cbm)} links=${JSON.stringify(s.site && s.site.links)} hdr=${s.site && s.site.headerLinks}`); console.log(`  reload: ${JSON.stringify(s.afterReload && s.afterReload.tabs && s.afterReload.tabs[0])} gallery: ${JSON.stringify(s.afterReloadGallery && s.afterReloadGallery.tabs && s.afterReloadGallery.tabs[0])} ${s.afterReloadGallery && s.afterReloadGallery.url}`); console.log(`  siteTick=${s.siteTick && t(s.siteTick.toast)} X=${b(s.XafterSite)} Y=${b(s.YafterSite)} restore=${s.siteRestore && t(s.siteRestore.toast)} final=${b(s.siteGaFinal)}`); if (f['separate-error']) console.log('  ERR', f['separate-error'].slice(0, 200)); }
    if (f.theme) { const s = f.theme; const h = (x) => x && `${x.status} font=${(x.bodyFont || '').slice(0, 20)} sheets=${(x.sheets || []).length} struct=${x.structure}`; console.log(`theme: before ${h(s.homeBefore)} | untick window=${JSON.stringify(s.untick.window && s.untick.window.text)} toast=${t(s.untick.toast)} | reload=${b(s.rowAfterReload)} | themeTab before=${JSON.stringify(s.themeTabBefore.selects)} after=${JSON.stringify(s.themeTabAfter.selects)} "${s.themeTabAfter.text}" | homeAfter ${h(s.homeAfter)} about ${h(s.aboutAfter)} login ${h(s.loginAfter)} | retick ${t(s.retick.toast)} | restored ${h(s.homeRestored)}`); }
    if (f.wizard) { const w = f.wizard; console.log(`wizard: tabs=${JSON.stringify(w.wizard.tabs && [w.wizard.tabs[0], w.wizard.tabs[w.wizard.tabs.length - 1]])} hdr=${w.wizard.headerLinks} rows=${w.wizard.rows} usage=${b(w.wizard.usage)} wf=${JSON.stringify(w.wizard.links.webfeedplugin.links)} tick=${t(w.wizardTick.toast)} website=${b(w.websiteAfterWizard)} untickSite=${t(w.websiteUntick.toast)} wizardAfter=${b(w.wizardAfterWebsite)} leave=${JSON.stringify(w.wizardLeave)}`); }
    if (f.noadmin) { const n = f.noadmin; console.log(`noadmin: removeRole=${n.removeRole} after=${JSON.stringify((n.rolesAfter || []).map((x) => x.slice(0, 30)))}`); console.log(`  website: denied=${n.website.denied} url=${n.website.url} err=${n.website.errorWindow} tab=${n.website.pluginsTab} tick=${n.website.tick && JSON.stringify({toast: t(n.website.tick.toast), after: n.website.tick.after, err: n.website.tick.errorWindow, body: n.website.tick.bodies})}`); const w = n.wizard || {}; console.log(`  wizard: tabs=${JSON.stringify(w.tabs && w.tabs[0])} usage=${b(w.usage)} links=${JSON.stringify(w.links && Object.fromEntries(Object.entries(w.links).map(([k, v]) => [k, v.links || v])))} tick=${w.tickGA && JSON.stringify({toast: t(w.tickGA.toast), after: w.tickGA.after, err: w.tickGA.errorWindow, body: w.tickGA.bodies})} untick=${w.untickWF && JSON.stringify({toast: t(w.untickWF.toast), after: w.untickWF.after, err: w.untickWF.windowAfter3s, body: w.untickWF.bodies})} reload=${w.afterReload && JSON.stringify([b(w.afterReload.ga), b(w.afterReload.wf)])}`); }
    if (f.permit) console.log('permit:', JSON.stringify(f.permit));
    if (f.omp1) console.log(`omp1: contexts=${f.omp1.contexts} pk=${b(f.omp1.pk)} X=${b(f.omp1.X)}`);
    if (f.single) console.log(`single: contexts=${f.single.contexts} siteTabs=${JSON.stringify(f.single.siteTabs && f.single.siteTabs[0])} usage=${b(f.single.usageEvent)}`);
}
